// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLt5zAnU0Xb3B73abYVCzw7Qqa4gGZI9A',
    appId: '1:460973357582:web:53c795e80676df45ad9a5f',
    messagingSenderId: '460973357582',
    projectId: 'to-do-app-50434',
    authDomain: 'to-do-app-50434.firebaseapp.com',
    storageBucket: 'to-do-app-50434.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9fs_szlfjdOMdUY9d8vYHaCnWmQutfjw',
    appId: '1:460973357582:android:194f1fff234f7935ad9a5f',
    messagingSenderId: '460973357582',
    projectId: 'to-do-app-50434',
    storageBucket: 'to-do-app-50434.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_sJDoorJKrE2tWqi0tm0iH4jSqRyTavg',
    appId: '1:460973357582:ios:ad6b807a95246e63ad9a5f',
    messagingSenderId: '460973357582',
    projectId: 'to-do-app-50434',
    storageBucket: 'to-do-app-50434.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_sJDoorJKrE2tWqi0tm0iH4jSqRyTavg',
    appId: '1:460973357582:ios:ad6b807a95246e63ad9a5f',
    messagingSenderId: '460973357582',
    projectId: 'to-do-app-50434',
    storageBucket: 'to-do-app-50434.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLt5zAnU0Xb3B73abYVCzw7Qqa4gGZI9A',
    appId: '1:460973357582:web:fb1a632e9fe601ecad9a5f',
    messagingSenderId: '460973357582',
    projectId: 'to-do-app-50434',
    authDomain: 'to-do-app-50434.firebaseapp.com',
    storageBucket: 'to-do-app-50434.firebasestorage.app',
  );

}